### ISSUE TITLE
[Question] Steps to build and run rng-test.

### ISSUE THREAD

**Issue by denisacostaq** [trezor/rng-test#2]
There is any guide to run this firmware in the device?
I'am unable to build the project, this depends on libopencm3 but it's not pointing to any specific release([no releases from libopencm so far I can see](https://github.com/libopencm3/libopencm3/releases)) or hash.

if I can run the firmware as I can verify it? that it's running?

Thank you in advance.

**Comment by prusnak** [comment]
Just use master of libopencm3
